# Header

menu:
  主页: /
  随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/dependmyse"
  weibo: "http://weibo.com/p/1005052143627101/home"
  rss: "#"
  zhihu: "https://www.zhihu.com/people/dependmyse"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 阅读更多
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: 'http://tva2.sinaimg.cn/crop.0.0.180.180.180/7fc5275djw1e8qgp5bmzyj2050050aa8.jpg'

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: dependmyse

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  #friends: '友链'
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: 爱编程，爱晚起，<br>偶尔也忙到深夜，<br>喜欢学习，努力工作，<br>也享受生活，<br>我酷爱技术，<br>崇尚简单的快乐和幸福，<br>我不是码农，我是程序员，<br>我和你一样，为理想而奋斗！
